Revert "style: Run shfmt on workflows and actions (#114)"
This reverts commit cba1f0891650baf1a9c88624dc2d72573be2eb81.

diff --git a/.github/workflows/check-pr-title.yml b/.github/workflows/check-pr-title.yml
--- a/.github/workflows/check-pr-title.yml
+++ b/.github/workflows/check-pr-title.yml
@@ -30,6 +30,6 @@ jobs:
           TITLE: ${{ github.event.pull_request.title }}
         run: |
           if [[ ! "${TITLE}" =~ ^[a-z]+:\ [\[A-Z] ]]; then
-              echo "Error: Title must start with an uppercase letter after the prefix."
-              exit 1
+            echo "Error: Title must start with an uppercase letter after the prefix."
+            exit 1
           fi
diff --git a/.github/workflows/test-create-issue.yml b/.github/workflows/test-create-issue.yml
--- a/.github/workflows/test-create-issue.yml
+++ b/.github/workflows/test-create-issue.yml
@@ -38,7 +38,7 @@ jobs:
         id: write_body_file
         shell: bash
         run: |
-          echo "This issue was created by a test workflow for the create-issue action from body file." >test_issue_body.md
+          echo "This issue was created by a test workflow for the create-issue action from body file." > test_issue_body.md
 
       - name: Create an issue 2
         id: create_issue_2
@@ -59,6 +59,6 @@ jobs:
 
           # Check second issue is next number after first issue
           if [ $((ISSUE_NUMBER_1 + 1)) -ne $ISSUE_NUMBER_2 ]; then
-              echo "Error: Issue numbers are not sequential."
-              exit 1
+            echo "Error: Issue numbers are not sequential."
+            exit 1
           fi
