style: Run shfmt on workflows and actions (#114)

diff --git a/.github/workflows/test-get-nproc.yml b/.github/workflows/test-get-nproc.yml
--- a/.github/workflows/test-get-nproc.yml
+++ b/.github/workflows/test-get-nproc.yml
@@ -63,22 +63,22 @@ jobs:
         run: |
           echo "NPROC without subtraction: ${WITHOUT_SUB}"
           if [ ${WITHOUT_SUB} -lt 1 ]; then
-            echo "Expected at least 1 processor before subtraction."
-            exit 1
+              echo "Expected at least 1 processor before subtraction."
+              exit 1
           fi
 
           echo "NPROC with small subtraction: ${WITH_SUB}"
           if [ ${WITH_SUB} -lt 1 ]; then
-            echo "Expected at least 1 processor after subtraction."
-            exit 1
+              echo "Expected at least 1 processor after subtraction."
+              exit 1
           fi
 
-          if (( ${WITHOUT_SUB} - ${SUBTRACTION} != ${WITH_SUB} )); then
-            echo "Expected ${WITHOUT_SUB}-${SUBTRACTION}=${WITH_SUB}."
-            exit 1
+          if ((${WITHOUT_SUB} - ${SUBTRACTION} != ${WITH_SUB})); then
+              echo "Expected ${WITHOUT_SUB}-${SUBTRACTION}=${WITH_SUB}."
+              exit 1
           fi
 
           if [ '${{ steps.with-large-subtraction.outcome }}' != 'failure' ]; then
-            echo "Expected large subtraction to fail."
-            exit 1
+              echo "Expected large subtraction to fail."
+              exit 1
           fi
